build:
	go build -o bin/hw2 hw2.go
run:
	go run hw2.go
compile:
	# macOS
	GOOS=darwin GOARCH=amd64 go build -o bin/hw2DarwinAmd64 hw2.go
	# Linux
	GOOS=linux GOARCH=amd64 go build -o bin/hw2LinuxAmd64 hw2.go
	# Windows
	GOOS=windows GOARCH=amd64 go build -o bin/hw2WindowsAmd64 hw2.go
